name = "QuadraticModelsGurobi"
uuid = "b0275aa7-013b-42ad-9e10-dc5d6db0accb"
authors = ["Geoffroy Leconte <gleconte50@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
SolverTools = "b5612192-2639-5dc1-abfe-fbedd65fab29"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Gurobi = "0.9"
julia = "1"

[extras]
QPSReader = "10f199a5-22af-520b-b891-7ce84a7b1bd0"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "QPSReader", "QuadraticModels"]
